openapi: 3.0.2
info:
  title: Resource Tracking API
  description: Skedulo Resource Tracking API
  version: 1.0.0
paths:
  /location/latest:
    get:
      security:
        - Authorization: []
      operationId: locationLatest
      summary: Latest locations
      description: >
        The latest locations endpoint returns information about the
        **resource's** latest location. It is a map from resourceId to latest
        location.
      parameters:
        - name: resource_ids
          in: query
          description: Comma separated resourceIds
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: A map from resourceId to Latest Location
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    $ref: '#/components/schemas/LatestLocationResult'
            result:
              examples:
                response:
                  value:
                    a0L6F000018s95jUAA:
                      time: '2017-02-08T05:20:45.550Z'
                      lat: 51.503364
                      lng: -0.127625
                      accuracy: 2.5
        '400':
          description: Bad request. eg. resourceId cannot be empty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /location/history:
    get:
      security:
        - Authorization: []
      operationId: locationHistory
      summary: Location history
      description: >
        The Location history end point allows you to retrieve the location
        history for a resource.

        The default limit is 100 results.
      parameters:
        - name: resource_id
          in: query
          description: Identifier of a resource
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: Start time
          required: true
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: End Time
          required: true
          schema:
            type: string
            format: date-time
        - name: accuracy
          in: query
          description: >-
            All points returned will have an accuracy of at least the number
            given. If this parameter is not provided the default value is 100.
            To return all points use an empty string.
          required: false
          schema:
            type: number
            format: double
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Paged array of locations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultLocationHistory'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /location/update:
    post:
      security:
        - Authorization: []
      operationId: locationUpdate
      summary: Location Update
      description: >
        The location update endpoint allows one or more position updates to be
        provided indicating a resource's location.


        The resource is determined by the Java Web Token provided. It is not
        possible for users other than the logged in user to update a resources
        position.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Location'
        required: true
      responses:
        '200':
          description: Location update added
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /location/resources_within_distance:
    get:
      security:
        - Authorization: []
      summary: Locate resources with a set distance
      description: Locate all resources within a set distance of a specified location.
      operationId: locationResourcesWithinDistance
      parameters:
        - name: lat
          in: query
          required: true
          description: >
            The latitude (degrees).  This should be in decimal format, ie.
            "DDD.DDDD" not degrees and minutes.
          schema:
            type: number
            format: double
        - name: lng
          in: query
          required: true
          description: >
            The longitude of the position (degrees).  This should be in decimal
            format, ie. "DDD.DDDD" not degrees and minutes.
          schema:
            type: number
            format: double
        - name: distance
          in: query
          required: true
          description: >-
            The distance (metres) to query for resources.  Note that the
            accuracy of the resources location is not considered when making
            this query.
          schema:
            type: number
            format: double
        - name: start
          in: query
          description: Only consider points after this time.
          required: false
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: Only consider points before this time.
          required: false
          schema:
            type: string
            format: date-time
        - name: accuracy
          in: query
          description: >-
            Ignores any points that have an accuracy greater than the number
            given. If this parameter is not provided the default value is 100.
            To return all points use an empty string.
          required: false
          schema:
            type: number
            format: double
      responses:
        '200':
          description: >-
            Resources and their latest position that was within distance of the
            location.
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    $ref: '#/components/schemas/ResourceDistanceFromLocationResult'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /travel/routes:
    get:
      security:
        - Authorization: []
      operationId: travelRoutes
      summary: Retrieve historical routes for one or more resources.
      description: >
        Given a comma-separated list of resource Ids and a start and end date,
        return the route taken by that resource between the start and end time.


        The maximum amount of time supported is 24 hours.


        The supported formats are

        * _polyline_ Uses the Google Maps Polyline encoding (default)

        * _wkt_ - Well Known Text Strings.  Either a LINESTRING or a POINT is
        returned

        * _geojson_ - GeoJSON format. Either a linestring or a point is returned
      parameters:
        - name: resource_ids
          in: query
          description: Comma separated resource Id values
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: Start time
          required: true
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: End Time
          required: true
          schema:
            type: string
            format: date-time
        - name: accuracy
          in: query
          description: >-
            All points returned will have an accuracy of at least the number
            given. If this parameter is not provided the default value is 100.
            To return all points use an empty string.
          required: false
          schema:
            type: number
            format: double
        - name: format
          in: query
          description: Output Format.
          schema:
            type: string
            enum:
              - polyline
              - wkt
              - geojson
      responses:
        '200':
          description: Map from resourceId to route in the requested format
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    $ref: '#/components/schemas/RouteResult'
            polyline:
              examples:
                response:
                  value:
                    result:
                      a0L6F000018s95jUAA:
                        start: '2017-02-13T01:41:01.629Z'
                        end: '2017-02-14T09:46:35.296Z'
                        polyline: _gjyHr|W[gBo|RgT
            WKT:
              examples:
                response:
                  value:
                    result:
                      a0L6F000018s95jUAA:
                        start: '2017-02-13T01:41:01.629Z'
                        end: '2017-02-14T09:46:35.296Z'
                        wkt: >-
                          LINESTRING(51.503364 -0.127625,51.5035 -0.1271,51.6055
                          -0.1237)
            WKT (With a Point):
              examples:
                response:
                  value:
                    result:
                      a0L6F000018s95jUAA:
                        start: '2017-02-13T01:41:01.629Z'
                        end: '2017-02-13T01:41:01.629Z'
                        wkt: POINT(51.503364 -0.127625)
            GeoJSON:
              examples:
                response:
                  value:
                    result:
                      a0L6F000018s95jUAA:
                        start: '2017-02-13T01:41:01.629Z'
                        end: '2017-02-14T09:46:35.296Z'
                        geoJson:
                          type: LineString
                          coordinates:
                            - - 51.503364
                              - -0.127625
                            - - 51.5035
                              - -0.1271
                            - - 51.6055
                              - -0.1237
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
servers:
  - url: https://api.skedulo.com/resource_tracking
  - url: https://api.uk.skedulo.com/resource_tracking
  - url: https://api.ca.skedulo.com/resource_tracking
  - url: https://api.au.skedulo.com/resource_tracking
components:
  securitySchemes:
    Authorization:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Location:
      type: object
      required:
        - time
        - lat
        - lng
      properties:
        time:
          type: string
          format: date-time
          description: Time the location was recorded. This must be in ISO date format.
        lat:
          type: number
          format: double
          description: >
            The latitude (degrees).  This should be in decimal format, ie.
            "DDD.DDDD" not degrees and minutes.
        lng:
          type: number
          format: double
          description: >
            The longitude (degrees). This should be in decimal format, ie.
            "DDD.DDDD" not degrees and minutes.
        altitude:
          type: number
          format: float
          description: The altitude (m)
        heading:
          type: number
          format: float
          minimum: 0
          maximum: 360
          description: >
            The current heading/bearing of the path track (degrees).  Where both
            bearing and orientation are available, the bearing should be used. 
            This distinguishes the current orientation of the device which  may
            be determined by compass for example from the heading of the track
            taken as the user moves.
        speed:
          type: number
          format: float
          minimum: 0
          description: The current speed (m/s).
        accuracy:
          type: number
          format: float
          minimum: 0
          description: |
            Horizontal position accuracy (m).
        altAccuracy:
          type: number
          format: float
          minimum: 0
          description: |
            Vertical position accuracy (m).
    LatestLocationResult:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Location'
    LocationHistoryResult:
      type: object
      description: Map resource ids to an array of LocationHistory items
      additionalProperties:
        type: array
        items:
          $ref: '#/components/schemas/Location'
    Paging:
      type: object
      required:
        - total
        - offset
        - limit
      properties:
        total:
          type: number
          format: int64
        offset:
          type: number
          format: int64
        limit:
          type: number
          format: int64
    PagedResultLocationHistory:
      type: object
      required:
        - paging
        - result
      properties:
        paging:
          $ref: '#/components/schemas/Paging'
        result:
          $ref: '#/components/schemas/LocationHistory'
    LocationHistory:
      type: array
      items:
        $ref: '#/components/schemas/Location'
    ResourceDistanceFromLocationResult:
      type: object
      description: Map resource ids to their distance from a location
      additionalProperties:
        $ref: '#/components/schemas/DistanceFromLocation'
    DistanceFromLocation:
      type: object
      description: Position and Distance from a location
      required:
        - time
        - lat
        - lng
        - distance
      properties:
        time:
          type: string
          format: date-time
          description: Time the last position was received
        lat:
          type: number
          format: double
          description: Latitude of the position
        lng:
          type: number
          format: double
          description: Longitude of the position
        distance:
          type: number
          format: double
          description: Distance from the requested location (in meters)
        accuracy:
          type: number
          format: double
          description: Accuracy of the position
    RouteResult:
      type: object
      description: Map resource ids to routes with start and end times
      required:
        - result
      properties:
        result:
          $ref: '#/components/schemas/RouteForResource'
    RouteForResource:
      type: object
      description: Map resource ids to route information
      additionalProperties:
        $ref: '#/components/schemas/Route'
    Route:
      type: object
      description: >-
        Route Information for a given resource.  One of polyline, wkt, or
        geoJson should be present
      required:
        - start
        - end
      properties:
        start:
          type: string
          format: date-time
          description: Time of the first position in the result
        end:
          type: string
          format: date-time
          description: Time of the last position in the result
        polyline:
          type: string
          format: Google Maps Polyline
          description: The route encoded as a Google maps polylne
        wkt:
          type: string
          format: Well Known Text
          description: >-
            The route encoded in Well Known Text (wkt) format. Either POINT or
            LINESTRING will be returned
        geoJson:
          type: object
          format: GeoJson
          description: GeoJSON encoded point or linestring
    TravelDistanceResult:
      type: object
      description: Map resource ids to distances with start and end times
      required:
        - result
      properties:
        result:
          $ref: '#/components/schemas/TravelDistance'
    TravelDistance:
      type: object
      properties:
        start:
          type: string
          format: date-time
          description: Time of the first position in the result
        end:
          type: string
          format: date-time
          description: Time of the last position in the result
        distance:
          type: number
          format: double
          description: Distance travelled in the time (m)
    JobEvent:
      type: object
      description: Information about an event that was tracked against a job
      required:
        - resourceId
        - time
        - event
      properties:
        resourceId:
          type: string
        time:
          type: string
          format: date-time
          description: Time the event occurred
        event:
          type: string
          description: Identifies the event type
        data:
          $ref: '#/components/schemas/EventData'
    ResourceJobEvent:
      type: object
      description: Information about an event that was tracked against a job for a resource
      required:
        - jobId
        - time
        - event
      properties:
        jobId:
          type: string
        time:
          type: string
          format: date-time
          description: Time the event occurred
        event:
          type: string
          description: Identifies the event type
        data:
          $ref: '#/components/schemas/EventData'
    EventUpdate:
      type: object
      description: Information about an event that occurred
      required:
        - time
        - event
      properties:
        time:
          type: string
          format: date-time
          description: Time the event occurred
        event:
          type: string
          description: >
            Identifies the event type.  This is a free string, however the
            following event types are currently expected.

            Job Status events:

              * CHECKEDIN
              * COMPLETE
              * CONFIRMED
              * DECLINED
              * INPROGRESS
              * ENROUTE
              * COMPLETED

            Tracking state events:

              * TRACKING_ENABLED
              * TRACKING_DISABLED
        location:
          $ref: '#/components/schemas/Location'
        data:
          $ref: '#/components/schemas/EventData'
    EventData:
      type: object
      description: Additional Event data
      properties:
        jobId:
          type: string
          description: The job id
        jobAllocationId:
          type: string
          description: The job allocation id
        destination:
          $ref: '#/components/schemas/Destination'
      additionalProperties: true
    Destination:
      type: object
      description: Location of a destination
      properties:
        name:
          type: string
          description: An identifying name
        address:
          type: string
          description: Street address of destination
        lat:
          type: number
          format: double
          description: Latitude of the destination
        lng:
          type: number
          format: double
          description: Longitude of the destination
    JobSummaryResult:
      type: object
      required:
        - result
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/JobSummary'
    JobSummary:
      type: object
      description: Summary of a job
      required:
        - jobId
        - resourceId
        - totalLength
        - totalDistance
      properties:
        jobId:
          type: string
          description: Identifier of the job
        resourceId:
          type: string
          description: Identifier of the resource
        arrived:
          type: string
          format: date-time
          description: When the resource arrived at the job
        departed:
          type: string
          format: date-time
          description: When the resource departed the job
        events:
          type: array
          items:
            $ref: '#/components/schemas/JobEventSummary'
          description: >-
            Summaries about each job status change. Only returned if the event
            query parameter is set.
        travelLength:
          type: number
          format: double
          description: The length of the route taken to the job
        travelDistance:
          type: number
          format: double
          description: >-
            The distance from the start of the route to the job in a straight
            line
        totalLength:
          type: number
          format: double
          description: The total length of the route travelled for each job status change
        totalDistance:
          type: number
          format: double
          description: >-
            The total distance in a straight line travelled for each job status
            change
        travelTime:
          type: number
          format: long
          description: >-
            The duration in seconds that it took for the resource to travel to
            the job
        serviceTime:
          type: number
          format: long
          description: The duration in seconds that it took to complete the job
    JobEventSummary:
      type: object
      description: Summary of the events for a job and resource
      required:
        - event
        - eventTime
        - trackTime
        - eventLocation
        - length
        - distance
      properties:
        event:
          type: string
          description: >-
            The event the object is summarising, one of 'ENROUTE', 'CHECKEDIN',
            'INPROGRESS' or 'COMPLETE'
        eventTime:
          type: string
          format: date-time
          description: When the resource flagged this event as occurring
        trackTime:
          type: string
          format: date-time
          description: When the location tracking event occurred
        eventLocation:
          $ref: '#/components/schemas/LatLng'
        nextEvent:
          type: string
          description: >-
            The next event after this one, one of 'ENROUTE', 'CHECKEDIN',
            'INPROGRESS' or 'COMPLETE'. Can be null if it is the last event.
        duration:
          type: number
          format: long
          description: The duration in seconds that the resource spent at this event
        length:
          type: number
          format: double
          description: The length of the route taken during the event
        distance:
          type: number
          format: double
          description: >-
            The distance from the first location to the last location in a
            straight line
    LatLng:
      type: object
      required:
        - lat
        - lng
      properties:
        lat:
          type: number
          format: double
          description: Latitude of the position
        lng:
          type: number
          format: double
          description: Longitude of the position
    Error:
      type: object
      properties:
        errorType:
          type: string
        message:
          type: string
